import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, Check, Menu, X } from "lucide-react";
import Hero from "./Hero";
import { TALENT_PATH, Link, currentPath } from "./router";

const schema = { "@context": "https://schema.org", "@type": "Organization", name: "Nexova", description: "Consultora de recursos humanos y adquisición de talento", url: "https://nexova.com", foundingDate: "2011", address: [{ "@type": "PostalAddress", addressCountry: "ES", addressLocality: "Valencia", addressRegion: "Comunidad Valenciana" }, { "@type": "PostalAddress", addressCountry: "US", addressLocality: "Miami", addressRegion: "Florida" }], contactPoint: { "@type": "ContactPoint", telephone: "+34-960-123-456", contactType: "customer service", availableLanguage: ["Spanish", "English"] }, sameAs: ["https://linkedin.com/company/nexova", "https://instagram.com/nexova"] };

type FormData = { fullName: string; email: string; phone: string; country: string; experience: string; sector: string; english: string; availability: string; linkedin: string; comments: string; consent: boolean };
const initial: FormData = { fullName: "", email: "", phone: "", country: "", experience: "", sector: "", english: "", availability: "", linkedin: "", comments: "", consent: false };

const inputClass = "mt-2 w-full rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-white";

function TalentForm() {
  const [data, setData] = useState(initial); const [errors, setErrors] = useState<Record<string, string>>({}); const [sent, setSent] = useState(false);
  const update = (key: keyof FormData, value: string | boolean) => setData((old) => ({ ...old, [key]: value }));
  const validate = () => { const e: Record<string, string> = {}; if (data.fullName.trim().split(/\s+/).length < 2) e.fullName = "El nombre debe contener al menos nombre y apellido"; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) e.email = "Ingresa un email válido (ejemplo: nombre@empresa.com)"; if (!/^\+\d{1,3}\s[\d\s]{6,14}$/.test(data.phone)) e.phone = "El teléfono debe incluir código de país (ejemplo: +34 612 345 678)"; if (!data.country) e.country = "Selecciona tu país de residencia"; if (data.experience === "" || +data.experience < 0 || +data.experience > 50) e.experience = "Los años de experiencia deben estar entre 0 y 50"; if (!data.sector) e.sector = "Selecciona el sector de tu interés"; if (!data.english) e.english = "Indica tu nivel de inglés"; if (!data.availability) e.availability = "Selecciona tu disponibilidad"; if (data.linkedin && !/^https?:\/\//.test(data.linkedin)) e.linkedin = "Si incluyes LinkedIn, debe ser una URL válida"; if (data.comments.length > 500) e.comments = `Los comentarios no pueden exceder 500 caracteres (quedan ${500 - data.comments.length})`; if (!data.consent) e.consent = "Debes aceptar la política de tratamiento de datos para continuar"; return e; };
  const submit = (event: FormEvent) => { event.preventDefault(); const e = validate(); setErrors(e); if (!Object.keys(e).length) setSent(true); };
  // The form does not send anything yet (there is no endpoint), so it must not say that it did: it says what to do instead.
  if (sent) return <div className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-8" role="status"><h3 className="text-2xl font-bold text-white">Tus datos son correctos, pero todavía no se han enviado</h3><p className="mt-3 text-slate-300">El envío en línea de este formulario aún no está disponible. Para que nuestro equipo de selección conozca tu perfil, escríbenos a <a className="text-cyan-300 underline" href="mailto:contacto@nexova.com">contacto@nexova.com</a> con tu información y, si puedes, tu CV.</p><button type="button" onClick={() => setSent(false)} className="mt-6 rounded-full border border-slate-600 px-5 py-2 text-sm text-slate-100 hover:border-cyan-400">Volver al formulario</button></div>;
  // Enlaza cada mensaje de error con su campo para lectores de pantalla.
  const errId = (name: string) => `error-${name}`;
  const a11y = (name: keyof FormData) => ({ "aria-invalid": errors[name] ? true : undefined, "aria-describedby": errors[name] ? errId(name) : undefined });
  const field = (name: keyof FormData) => errors[name] && <p id={errId(name)} className="mt-1 text-sm text-rose-300" role="alert">{errors[name]}</p>;
  const selects: [keyof FormData, string, string[]][] = [["country", "País de residencia", ["España", "Estados Unidos", "Otro"]], ["sector", "Sector de interés", ["Tecnología", "Retail", "Servicios Financieros", "Consultoría", "Otro"]], ["english", "Nivel de inglés", ["Básico", "Intermedio", "Avanzado", "Nativo"]]];
  return <form onSubmit={submit} noValidate className="grid gap-5 md:grid-cols-2">{([["fullName", "Nombre completo", "text"], ["email", "Email", "email"], ["phone", "Teléfono", "tel"]] as const).map(([name, label, type]) => <label key={name} className="text-sm text-slate-200">{label} *<input type={type} value={data[name]} onChange={(e) => update(name, e.target.value)} className={inputClass} {...a11y(name)} />{field(name)}</label>)}
  {selects.map(([name, label, options]) => <label key={name} className="text-sm text-slate-200">{label} *<select value={data[name] as string} onChange={(e) => update(name, e.target.value)} className={inputClass} {...a11y(name)}><option value="">Selecciona una opción</option>{options.map((option) => <option key={option}>{option}</option>)}</select>{field(name)}</label>)}
  <label className="text-sm text-slate-200">Años de experiencia *<input type="number" min="0" max="50" value={data.experience} onChange={(e) => update("experience", e.target.value)} className={inputClass} {...a11y("experience")} />{field("experience")}</label><fieldset {...a11y("availability")}><legend className="text-sm text-slate-200">Disponibilidad *</legend><div className="mt-2 grid gap-2 text-sm text-slate-300">{["Inmediata", "1 mes", "2-3 meses", "Solo explorando"].map((option) => <label key={option}><input type="radio" name="availability" checked={data.availability === option} onChange={() => update("availability", option)} className="mr-2" />{option}</label>)}</div>{field("availability")}</fieldset>
  <label className="text-sm text-slate-200">LinkedIn (URL del perfil)<input type="url" value={data.linkedin} onChange={(e) => update("linkedin", e.target.value)} className={inputClass} {...a11y("linkedin")} />{field("linkedin")}</label><label className="text-sm text-slate-200 md:col-span-2">Comentarios adicionales<textarea maxLength={500} value={data.comments} onChange={(e) => update("comments", e.target.value)} rows={4} className={inputClass} {...a11y("comments")} /><span className="text-xs text-slate-400">{data.comments.length}/500</span>{field("comments")}</label><label className="md:col-span-2 text-sm text-slate-300"><input type="checkbox" checked={data.consent} onChange={(e) => update("consent", e.target.checked)} className="mr-2" {...a11y("consent")} />Acepto la política de tratamiento de datos *{field("consent")}</label><button className="w-fit rounded-full bg-cyan-400 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-300" type="submit">Enviar mi perfil <ArrowRight className="ml-2 inline" size={18} /></button></form>;
}

const services = [["Headhunting Ejecutivo", ["Búsqueda y selección de perfiles ejecutivos y mandos medios", "Proceso personalizado con garantía de reemplazo"]], ["Outsourcing de Atención al Cliente", ["Equipos especializados para empresas tecnológicas", "Formación continua y supervisión dedicada"]], ["Formación Corporativa", ["Programas de soft skills y liderazgo", "Cursos presenciales y en línea adaptados a cada organización"]]] as const;

export default function App() {
  const [menu, setMenu] = useState(false); const [path, setPath] = useState(currentPath);
  const sync = () => { setPath(currentPath()); setMenu(false); };
  useEffect(() => { window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync); }, []);
  // Tras navegar, baja a la sección del hash (o al inicio si no hay).
  useEffect(() => { const id = window.location.hash.slice(1); (id && document.getElementById(id)) ? document.getElementById(id)!.scrollIntoView() : window.scrollTo(0, 0); }, [path]);
  const nav = (to: string, label: string) => <Link to={to} onNavigate={sync}>{label}</Link>;
  const onTalent = path === TALENT_PATH;
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className="border-b border-slate-800 bg-slate-950/90"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5" aria-label="Navegación principal"><Link to="/" onNavigate={sync} className="text-2xl font-black tracking-tight text-white">nexova<span className="text-cyan-400">.</span></Link><button className="text-white md:hidden" onClick={() => setMenu(!menu)} aria-label="Abrir menú" aria-expanded={menu}>{menu ? <X /> : <Menu />}</button><div className={`${menu ? "flex" : "hidden"} absolute left-0 top-16 z-10 w-full flex-col gap-5 bg-slate-950 p-6 md:static md:flex md:w-auto md:flex-row md:bg-transparent`}>{nav("/", "Inicio")}{nav("/#servicios", "Servicios")}{nav(TALENT_PATH, "Talento")}{nav("/#contacto", "Contacto")}</div></nav></header>
  <main>{onTalent ? <section id="talento" className="px-6 py-24"><div className="mx-auto max-w-4xl"><p className="font-semibold text-cyan-400">Tu próximo paso</p><h1 className="mt-3 text-4xl font-bold text-white">Únete a nuestro banco de talento</h1><p className="mt-4 text-slate-300">Este formulario es para profesionales. ¿Eres una empresa buscando talento? Escríbenos a <a className="text-cyan-300" href="mailto:contacto@nexova.com">contacto@nexova.com</a></p><div className="mt-10"><TalentForm /></div></div></section> : <>
  <Hero onNavigate={sync} />
  <section id="servicios" className="bg-slate-900/70 px-6 py-24"><div className="mx-auto max-w-6xl"><p className="font-semibold text-cyan-400">Lo que hacemos</p><h2 className="mt-3 text-4xl font-bold text-white">Soluciones para hacer crecer tu organización</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{services.map(([title, points]) => <article key={title} className="rounded-2xl border border-slate-800 bg-slate-950 p-7"><h3 className="text-xl font-bold text-white">{title}</h3><ul className="mt-4 space-y-3 leading-relaxed text-slate-400">{points.map((point) => <li key={point}><Check className="mr-2 inline text-cyan-400" size={18} />{point}</li>)}</ul></article>)}</div></div></section>
  <section className="mx-auto grid max-w-6xl gap-12 px-6 py-24 md:grid-cols-2"><div><p className="font-semibold text-cyan-400">Por qué Nexova</p><h2 className="mt-3 text-4xl font-bold text-white">Experiencia que se nota en cada conexión</h2></div><ul className="grid gap-5 text-lg text-slate-300">{["12 años de experiencia en el mercado latinoamericano", "Presencia regional: España y Estados Unidos", "+500 procesos exitosos de selección completados", "Especialización sectorial en tecnología, retail y finanzas"].map((item) => <li key={item}><Check className="mr-3 inline text-cyan-400" />{item}</li>)}</ul></section>
  <section id="contacto" className="bg-slate-900/70 px-6 py-24"><div className="mx-auto max-w-6xl"><p className="font-semibold text-cyan-400">Contacto</p><h2 className="mt-3 text-4xl font-bold text-white">Hablemos</h2><ul className="mt-8 space-y-3 text-lg text-slate-300"><li>Email: <a className="text-cyan-300" href="mailto:contacto@nexova.com">contacto@nexova.com</a></li><li>Valencia: <a className="text-cyan-300" href="tel:+34960123456">+34 960 123 456</a></li><li>Miami: <a className="text-cyan-300" href="tel:+13055550191">+1 305 555 0191</a></li></ul></div></section></>}</main>
  <footer className="mx-auto max-w-6xl px-6 py-16"><div className="grid gap-8 md:grid-cols-3"><div><p className="text-2xl font-black text-white">nexova<span className="text-cyan-400">.</span></p><p className="mt-3 text-slate-400">© 2025 Nexova. Todos los derechos reservados.</p></div><div className="text-slate-300"><p>contacto@nexova.com</p><p className="mt-2">Valencia: +34 960 123 456</p><p className="mt-2">Miami: +1 305 555 0191</p></div><div className="flex gap-4"><a href="https://linkedin.com/company/nexova" aria-label="LinkedIn">LinkedIn</a><a href="https://instagram.com/nexova" aria-label="Instagram">Instagram</a></div></div></footer></>;
}
