import {
  type Candidate,
  type SelectionProcess,
  type Vacancy,
} from "./types/models";

export const testCandidates: Candidate[] = [
  {
    id: "C-2026-0101",
    fullName: "Ana Torres",
    email: "ana.torres@nexova.example",
    phone: "+56911112222",
    yearsOfExperience: 5,
    skills: ["TypeScript", "React", "Node.js", "PostgreSQL"],
    englishLevel: "C1",
    seniority: "Senior",
    currentSalary: 3600,
    expectedSalary: 4300,
    availability: "2 weeks",
    location: "Santiago, Chile",
    remoteOnly: true,
    status: "Active",
  },
  {
    id: "C-2026-0102",
    fullName: "Luis Mendoza",
    email: "luis.mendoza@nexova.example",
    phone: "+5491144455566",
    yearsOfExperience: 3,
    skills: ["JavaScript", "Vue", "Node.js", "MongoDB"],
    englishLevel: "B2",
    seniority: "Semi-Senior",
    currentSalary: 2500,
    expectedSalary: 3000,
    availability: "Immediate",
    location: "Buenos Aires, Argentina",
    remoteOnly: true,
    status: "In process",
  },
  {
    id: "C-2026-0103",
    fullName: "Camila Rojas",
    email: "camila.rojas@nexova.example",
    phone: "+56999888777",
    yearsOfExperience: 9,
    skills: ["Python", "Django", "AWS", "PostgreSQL"],
    englishLevel: "C2",
    seniority: "Lead",
    currentSalary: 5200,
    expectedSalary: 6200,
    availability: "1 month",
    location: "Santiago, Chile",
    remoteOnly: false,
    status: "Active",
  },
  {
    id: "C-2026-0104",
    fullName: "Pedro Silva",
    email: "pedro.silva@nexova.example",
    phone: "+555199998888",
    yearsOfExperience: 1,
    skills: ["HTML", "CSS", "JavaScript"],
    englishLevel: "B1",
    seniority: "Junior",
    currentSalary: 1200,
    expectedSalary: 1800,
    availability: "Immediate",
    location: "Porto Alegre, Brazil",
    remoteOnly: false,
    status: "Inactive",
  },
];

export const testVacancies: Vacancy[] = [
  {
    id: "V-2026-0201",
    title: "Senior Full Stack Developer",
    companyName: "Nexova",
    requiredSkills: ["TypeScript", "React", "Node.js"],
    preferredSkills: ["PostgreSQL", "Docker"],
    minYearsExperience: 4,
    maxYearsExperience: 8,
    requiredEnglishLevel: "B2",
    requiredSeniority: "Senior",
    salaryRangeMin: 3800,
    salaryRangeMax: 5200,
    isRemote: true,
    location: "Santiago, Chile",
    status: "Open",
  },
  {
    id: "V-2026-0202",
    title: "Data Analyst",
    companyName: "Nexova",
    requiredSkills: ["SQL", "Python"],
    preferredSkills: ["Power BI", "Pandas"],
    minYearsExperience: 2,
    maxYearsExperience: 5,
    requiredEnglishLevel: "B1",
    requiredSeniority: "Semi-Senior",
    salaryRangeMin: 2200,
    salaryRangeMax: 3200,
    isRemote: false,
    location: "Buenos Aires, Argentina",
    status: "In progress",
  },
  {
    id: "V-2026-0203",
    title: "Platform Engineer",
    companyName: "Nexova",
    requiredSkills: ["AWS", "Docker", "Kubernetes"],
    preferredSkills: ["Terraform", "Python"],
    minYearsExperience: 5,
    maxYearsExperience: 10,
    requiredEnglishLevel: "C1",
    requiredSeniority: "Lead",
    salaryRangeMin: 5000,
    salaryRangeMax: 7000,
    isRemote: true,
    location: "Santiago, Chile",
    status: "Open",
  },
];

export const testSelectionProcesses: SelectionProcess[] = [
  {
    id: "P-2026-0301",
    candidateId: "C-2026-0101",
    vacancyId: "V-2026-0201",
    stage: "Interview",
    score: 84,
    notes: "Buen equilibrio entre frontend y backend.",
    createdAt: new Date("2026-07-01T10:00:00.000Z"),
    updatedAt: new Date("2026-07-02T15:30:00.000Z"),
  },
  {
    id: "P-2026-0302",
    candidateId: "C-2026-0102",
    vacancyId: "V-2026-0202",
    stage: "Technical test",
    score: 74,
    notes: "Buena base analitica.",
    createdAt: new Date("2026-07-03T11:00:00.000Z"),
    updatedAt: new Date("2026-07-05T08:00:00.000Z"),
  },
  {
    id: "P-2026-0303",
    candidateId: "C-2026-0103",
    vacancyId: "V-2026-0203",
    stage: "Hired",
    score: 95,
    notes: "Perfil tecnico sobresaliente.",
    createdAt: new Date("2026-07-04T09:00:00.000Z"),
    updatedAt: new Date("2026-07-07T18:45:00.000Z"),
  },
];
